require "options"
require "keymaps"
require "plugins"
require "autopairs"
require 'lsp'
require 'completion'
require 'treesitter'
require 'telescope'
require 'bufferline_config'
require 'lualine_config'
require 'tree'
require 'which_key'
require 'null_ls'
