#!/bin/env bash

# git
alias gs='git status'
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias go='git checkout'
alias gk='gitk --all&'
alias gx='gitx --all'

# ruby
alias be='bundle exec'
alias bo='bundle open'
alias migrate='be rake db:migrate db:test:prepare'
alias remigrate='be rake db:migrate && be rake db:migrate:redo && be rake db:schema:dump db:test:prepare'

# tmux
alias tmux='TERM=xterm-256color tmux'
